#!/bin/bash
set -e

# Copy agent-summary to /tmp if it exists in workspace
if [ -f agent-summary.md ]; then
  cp agent-summary.md /tmp/agent-summary.md || true
fi

# Git operations
git add src/domain/ports/logging-port.interface.ts
git add src/application/settings/setting-definition.interface.ts
git add src/application/settings/log-level-setting.ts
git add src/application/use-cases/register-context-menu.use-case.ts
git add src/application/services/ModuleSettingsRegistrar.ts
git add src/infrastructure/logging/logger.interface.ts
git add src/infrastructure/shared/utils/validate-log-level.ts

# Commit
git commit -m "fix: Resolve issue #59 - Application Layer importiert Logger aus Infrastructure Layer

- Erstellt LoggingPort Interface im Domain Layer
- Application Layer verwendet jetzt Domain-Abstraktion statt Infrastructure-Interface
- Infrastructure-Interface erweitert LoggingPort für Rückwärtskompatibilität
- Behebt DIP-Verletzung gemäß Clean Architecture

Closes #59"

# Push
git push origin fix/issue-59--architecture-violation-application-settings-setti

# Create PR body
PR_BODY_FILE="/tmp/pr-body.txt"
cat > "$PR_BODY_FILE" << 'PRBODY'
## 🤖 AI-Generated Fix for Issue #59

This PR was automatically generated by the AI Issue Fix workflow to resolve issue #59.

**Issue:** [ARCHITECTURE_VIOLATION] application-settings-setting-definition.interface.ts:16 - Application Layer importiert Logger aus Infrastructure Layer
**Issue URL:** https://github.com/Lewellyen/fvtt_relationship_app_module/issues/59

### Changes
This PR contains the AI-generated fix for the issue. Please review carefully before merging.

### Review Checklist
- [ ] Code changes are correct
- [ ] Tests pass (if applicable)
- [ ] No breaking changes introduced
- [ ] Follows project architecture patterns

---
*This PR was created automatically. Please review and test before merging.*
PRBODY

# Create PR
gh pr create \
  --title "fix: Resolve issue #59 - [ARCHITECTURE_VIOLATION] application-settings-setting-definition.interface.ts:16 - Application Layer importiert Logger aus Infrastructure Layer" \
  --body-file "$PR_BODY_FILE" \
  --base main \
  --head fix/issue-59--architecture-violation-application-settings-setti \
  --label "ai-generated" \
  --label "automated" || true

# Get PR number and comment on issue
PR_NUMBER=$(gh pr list --head fix/issue-59--architecture-violation-application-settings-setti --json number --jq '.[0].number' || echo "")
if [ -n "$PR_NUMBER" ]; then
  gh issue comment 59 --body "🤖 AI has created a fix for this issue: PR #$PR_NUMBER"
fi
