import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { generateTraceId, getTraceTimestamp } from "@/infrastructure/shared/utils/trace";

describe("Trace Utilities", () => {
  describe("generateTraceId", () => {
    beforeEach(() => {
      vi.useFakeTimers();
    });

    afterEach(() => {
      vi.useRealTimers();
    });

    it("should generate a trace ID with timestamp and random parts", () => {
      const now = Date.now();
      vi.setSystemTime(now);

      const traceId = generateTraceId();

      expect(traceId).toContain(`${now}-`);
      expect(traceId.split("-")).toHaveLength(2);
    });

    it("should generate unique trace IDs for concurrent calls", () => {
      const now = Date.now();
      vi.setSystemTime(now);

      const traceId1 = generateTraceId();
      const traceId2 = generateTraceId();
      const traceId3 = generateTraceId();

      // All should have the same timestamp part
      expect(traceId1.split("-")[0]).toBe(`${now}`);
      expect(traceId2.split("-")[0]).toBe(`${now}`);
      expect(traceId3.split("-")[0]).toBe(`${now}`);

      // But different random parts (with very high probability)
      const random1 = traceId1.split("-")[1];
      const random2 = traceId2.split("-")[1];
      const random3 = traceId3.split("-")[1];

      // Random parts should be different (probabilistically)
      const uniqueRandoms = new Set([random1, random2, random3]);
      expect(uniqueRandoms.size).toBeGreaterThan(1); // At least 2 different
    });

    it("should generate trace IDs with different timestamps over time", () => {
      vi.setSystemTime(1000000);
      const traceId1 = generateTraceId();

      vi.setSystemTime(2000000);
      const traceId2 = generateTraceId();

      const timestamp1 = traceId1.split("-")[0];
      const timestamp2 = traceId2.split("-")[0];

      expect(timestamp1).toBe("1000000");
      expect(timestamp2).toBe("2000000");
      expect(timestamp1).not.toBe(timestamp2);
    });

    it("should generate trace IDs with alphanumeric random parts", () => {
      const traceId = generateTraceId();
      const randomPart = traceId.split("-")[1]!;

      // Random part should be 8 characters of base36 (alphanumeric)
      expect(randomPart).toHaveLength(8);
      expect(randomPart).toMatch(/^[a-z0-9]+$/);
    });
  });

  describe("getTraceTimestamp", () => {
    it("should extract timestamp from valid trace ID", () => {
      const timestamp = getTraceTimestamp("1234567890-abc123de");

      expect(timestamp).toBe(1234567890);
    });

    it("should return null for invalid trace ID format (no hyphen)", () => {
      const timestamp = getTraceTimestamp("invalid_trace_id");

      expect(timestamp).toBeNull();
    });

    it("should return null for invalid trace ID format (multiple hyphens)", () => {
      const timestamp = getTraceTimestamp("123-456-789");

      expect(timestamp).toBeNull();
    });

    it("should return null for non-numeric timestamp part", () => {
      const timestamp = getTraceTimestamp("notanumber-abc123");

      expect(timestamp).toBeNull();
    });

    it("should handle trace IDs generated by generateTraceId", () => {
      const now = Date.now();
      vi.useFakeTimers();
      vi.setSystemTime(now);

      const traceId = generateTraceId();
      const extractedTimestamp = getTraceTimestamp(traceId);

      expect(extractedTimestamp).toBe(now);

      vi.useRealTimers();
    });

    it("should return null for empty string", () => {
      const timestamp = getTraceTimestamp("");

      expect(timestamp).toBeNull();
    });

    it("should return null when timestamp part is empty", () => {
      const timestamp = getTraceTimestamp("-abc123de");

      expect(timestamp).toBeNull();
    });

    it("should return null when random part is empty", () => {
      const timestamp = getTraceTimestamp("1234567890-");

      expect(timestamp).toBeNull();
    });
  });
});
