#!/usr/bin/env python3
"""
Erstellt eine PR-Body für den AI Issue Fix Workflow.
Behandelt sicher alle Sonderzeichen.
"""
import os
import sys

def create_pr_body():
    """Erstellt die PR-Body aus Environment-Variablen."""
    issue_num = os.environ.get('ISSUE_NUM', '')
    issue_title = os.environ.get('ISSUE_TITLE', '')
    issue_url = os.environ.get('ISSUE_URL', '')
    agent_summary_file = os.environ.get('AGENT_SUMMARY_FILE', '/tmp/agent-summary.md')

    if not issue_num:
        print("❌ Error: ISSUE_NUM environment variable not set", file=sys.stderr)
        sys.exit(1)

    # Versuche Agent-Zusammenfassung zu laden
    agent_summary = None
    if os.path.exists(agent_summary_file):
        try:
            with open(agent_summary_file, 'r', encoding='utf-8') as f:
                agent_summary = f.read().strip()
            print(f"✅ Loaded agent summary from {agent_summary_file}", file=sys.stderr)
        except Exception as e:
            print(f"⚠️ Could not read agent summary: {e}", file=sys.stderr)

    # Erstelle PR-Body
    if agent_summary:
        # Verwende Agent-Zusammenfassung als Basis
        pr_body = f"""## 🤖 AI-Generated Fix for Issue #{issue_num}

**Issue:** [{issue_title}]({issue_url})

---

{agent_summary}

---

### Review Checklist
- [ ] Code changes are correct
- [ ] Tests pass (if applicable)
- [ ] No breaking changes introduced
- [ ] Follows project architecture patterns

---
*This PR was created automatically by the AI Issue Fix workflow. Please review and test before merging.*"""
    else:
        # Fallback: Standard PR-Body
        pr_body = f"""## 🤖 AI-Generated Fix for Issue #{issue_num}

This PR was automatically generated by the AI Issue Fix workflow to resolve issue #{issue_num}.

**Issue:** {issue_title}
**Issue URL:** {issue_url}

### Changes
This PR contains the AI-generated fix for the issue. Please review carefully before merging.

### Review Checklist
- [ ] Code changes are correct
- [ ] Tests pass (if applicable)
- [ ] No breaking changes introduced
- [ ] Follows project architecture patterns

---
*This PR was created automatically. Please review and test before merging.*"""

    output_file = os.environ.get('OUTPUT_FILE', '/tmp/pr-body.txt')

    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(pr_body)
        print(f"✅ PR body created for issue #{issue_num} -> {output_file}", file=sys.stderr)
        # Nur auf stdout ausgeben wenn OUTPUT_FILE nicht gesetzt ist (für Rückwärtskompatibilität)
        if 'OUTPUT_FILE' not in os.environ:
            print(pr_body)
        sys.exit(0)
    except Exception as e:
        print(f"❌ Error writing PR body file: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    create_pr_body()

