#!/usr/bin/env python3
"""
Erstellt einen Fix-Prompt für den AI Issue Fix Workflow.
Behandelt sicher alle Sonderzeichen in Issue-Beschreibungen.
"""
import os
import sys

def create_fix_prompt():
    """Erstellt den Fix-Prompt aus Environment-Variablen."""
    issue_num = os.environ.get('ISSUE_NUM', '')
    issue_title = os.environ.get('ISSUE_TITLE', '')
    issue_url = os.environ.get('ISSUE_URL', '')
    issue_body = os.environ.get('ISSUE_BODY', '')
    branch_name = os.environ.get('BRANCH_NAME', '')
    base_branch = os.environ.get('BASE_BRANCH', 'main')

    if not issue_num:
        print("❌ Error: ISSUE_NUM environment variable not set", file=sys.stderr)
        sys.exit(1)

    prompt = f"""Du arbeitest in einem GitHub Actions Runner mit vollständigem Zugriff auf Git und GitHub CLI.

**WICHTIG - Terminal-Befehle:**
Du hast VOLLSTÄNDIGEN Zugriff auf die Shell und kannst ALLE Terminal-Befehle direkt ausführen!
- Verwende das `run_terminal_cmd` Tool für Git-Befehle: `git add`, `git commit`, `git push`
- Verwende das `run_terminal_cmd` Tool für GitHub CLI-Befehle: `gh pr create`, `gh issue comment`
- Die Shell-Umgebung ist vollständig konfiguriert: Git, GitHub CLI, alle Tools sind verfügbar
- Du kannst JEDEN Shell-Befehl ausführen - es gibt KEINE Einschränkungen!

**WICHTIG - Terminal-Befehle:**
Du arbeitest in einem GitHub Actions Runner. Du hast Zugriff auf Tools wie `run_terminal_cmd` für Terminal-Befehle.

**Versuche IMMER zuerst Terminal-Befehle direkt auszuführen:**
- Verwende `run_terminal_cmd` für Git-Befehle: `git add .`, `git commit -m "..."`, `git push origin {branch_name}`
- Verwende `run_terminal_cmd` für GitHub CLI-Befehle: `gh pr create ...`, `gh issue comment ...`

**FALLBACK - Falls Terminal-Befehle abgelehnt werden:**
Wenn `run_terminal_cmd` nicht funktioniert, erstelle ein Fallback-Script `/tmp/agent-commands.sh`:
1. Script mit `#!/bin/bash` beginnen
2. Alle Git- und GitHub CLI-Befehle hinzufügen
3. Script ausführbar machen: `chmod +x /tmp/agent-commands.sh`
4. Der Workflow führt das Script dann automatisch aus

**WICHTIG:** Versuche IMMER zuerst Terminal-Befehle direkt - nur wenn das nicht funktioniert, verwende das Fallback-Script!

# Aufgabe: Issue #{issue_num} beheben

**Issue-Titel:** {issue_title}
**Issue-URL:** {issue_url}

**Issue-Beschreibung:**
{issue_body}

## Deine Aufgabe:

1. **Analysiere das Problem** im Issue
2. **Finde die betroffenen Dateien** (nutze `git`, `gh`, oder lese Dateien direkt)
3. **Implementiere die Lösung** direkt im Code
4. **Erstelle Commits** mit `git add` und `git commit`
5. **Pushe die Änderungen** mit `git push` (Branch: {branch_name})
6. **Erstelle einen Pull Request** mit `gh pr create` und verlinke ihn mit dem Issue
7. **Teste deine Lösung** (falls Tests vorhanden sind)

## WICHTIG - Du MUSST folgendes tun:

### Git-Operationen:
- **WICHTIG:** Verwende das `run_terminal_cmd` Tool für ALLE Git-Befehle!
- **Git-Befehle ausführen:** Nutze `run_terminal_cmd` mit Befehlen wie `git add`, `git commit`, `git push`
- **Erstelle sinnvolle Commits:** Jeder Commit sollte eine logische Änderungseinheit sein
- **Commit-Messages:** Verwende klare, beschreibende Messages (z.B. "fix: resolve issue #{issue_num}")
- **Keine leeren Commits:** Nur committen wenn tatsächlich Änderungen gemacht wurden
- **Keine Force-Push:** Nutze normale `git push origin {branch_name}`
- **Git ist bereits konfiguriert:** User und Email sind gesetzt, du musst sie nicht nochmal setzen

### Pull Request erstellen:
**NACH dem Push der Änderungen MUSST du einen Pull Request erstellen:**

1. **PR-Titel:** `fix: Resolve issue #{issue_num} - {issue_title}`

2. **PR-Body:** Erstelle eine aussagekräftige Beschreibung:
   ```markdown
   ## 🤖 AI-Generated Fix for Issue #{issue_num}

   This PR was automatically generated by the AI Issue Fix workflow to resolve issue #{issue_num}.

   **Issue:** {issue_title}
   **Issue URL:** {issue_url}

   ### Changes
   This PR contains the AI-generated fix for the issue. Please review carefully before merging.

   ### Review Checklist
   - [ ] Code changes are correct
   - [ ] Tests pass (if applicable)
   - [ ] No breaking changes introduced
   - [ ] Follows project architecture patterns

   ---
   *This PR was created automatically. Please review and test before merging.*
   ```

3. **PR erstellen mit GitHub CLI:**
   **WICHTIG:** Verwende `run_terminal_cmd` für alle `gh`-Befehle!

   Zuerst PR-Body in Datei schreiben (verwende `write` Tool):
   - Erstelle `/tmp/pr-body.txt` mit dem PR-Body-Inhalt

   Dann PR erstellen (verwende `run_terminal_cmd`):
   ```
   gh pr create --title "fix: Resolve issue #{issue_num} - {issue_title}" --body-file /tmp/pr-body.txt --base {base_branch} --head {branch_name} --label "ai-generated" --label "automated"
   ```

   **WICHTIG:** Schreibe den PR-Body zuerst in eine Datei (`/tmp/pr-body.txt`), um Sonderzeichen-Probleme zu vermeiden!

4. **Issue verlinken:**
   Nach erfolgreicher PR-Erstellung füge einen Kommentar zum Issue hinzu (verwende `run_terminal_cmd`):
   ```
   gh issue comment {issue_num} --body "🤖 AI has created a fix for this issue: PR #<PR_NUMBER>"
   ```

   Ersetze `<PR_NUMBER>` mit der tatsächlichen PR-Nummer aus dem `gh pr create` Output.

5. **Labels prüfen:**
   Falls die Labels "ai-generated" oder "automated" nicht existieren, erstelle sie nicht - der Workflow kümmert sich darum.

## Git-Konfiguration:

Git ist bereits konfiguriert:
- User: github-actions[bot]
- Email: github-actions[bot]@users.noreply.github.com
- Branch: {branch_name}
- Remote: origin (bereits konfiguriert)

## Projektkontext:

Das Projekt verwendet:
- **Clean Architecture** mit 4 Schichten: Domain → Application → Infrastructure → Framework
- **Result-Pattern** statt Exceptions (siehe ADR-0001)
- **SOLID-Prinzipien** durchgängig
- **Port-Adapter-Pattern** für Foundry VTT Version-Kompatibilität
- **Dependency Inversion Principle (DIP)**: Abhängigkeiten nur zu Interfaces

## Code-Qualität:

- Halte dich an die bestehenden Architektur-Patterns
- Verwende das Result-Pattern für Fehlerbehandlung
- Respektiere die Schichttrennung (Clean Architecture)
- Füge Tests hinzu, wenn möglich

## ⚠️ KRITISCH - PR-ZUSAMMENFASSUNG ERSTELLEN (OBLIGATORISCH):

**DU MUSST DIESE DATEI ERSTELLEN:** `/tmp/agent-summary.md`

**WARUM:** Diese Datei wird automatisch als PR-Body verwendet. OHNE diese Datei wird der PR mit einem generischen Standard-Text erstellt, der keine Informationen über das Problem oder die Lösung enthält!

**WANN:** Erstelle diese Datei NACH den Code-Änderungen, aber VOR dem Commit!

**WIE:** Verwende das `write` Tool um die Datei `/tmp/agent-summary.md` zu erstellen!

**INHALT - MUSS DIESE STRUKTUR HABEN:**

```markdown
## Problem

[Kurze Beschreibung des Problems aus dem Issue]

## Lösung

[Erkläre wie du das Problem gelöst hast - welche Änderungen wurden gemacht?]

## Geänderte Dateien

- `pfad/zur/datei.ts`: [Was wurde geändert und warum]
- `pfad/zur/datei2.ts`: [Was wurde geändert und warum]

## Technische Details

[Architektur-Entscheidungen, Pattern-Verwendung, z.B. Result-Pattern, Clean Architecture, etc.]

## Review-Hinweise

[Besondere Überlegungen für den Reviewer, z.B. Breaking Changes, Tests, etc.]
```

**KRITISCH:**
- Diese Datei wird als PR-Body verwendet!
- OHNE diese Datei wird der PR mit einer generischen Beschreibung erstellt!
- Verwende das `write` Tool um `/tmp/agent-summary.md` zu erstellen!
- Schreibe die Zusammenfassung NACH den Code-Änderungen, aber VOR dem Commit!

## Zusammenfassung der Schritte - MUSS IN DIESER REIHENFOLGE AUSGEFÜHRT WERDEN:

1. ✅ Code-Änderungen implementieren (verwende `search_replace` oder `write` Tool)
2. ✅ **KRITISCH:** Erstelle `/tmp/agent-summary.md` mit dem `write` Tool (siehe Format unten) - DIESE DATEI WIRD ALS PR-BODY VERWENDET!
3. ✅ Commits erstellen (verwende `run_terminal_cmd` mit `git add` und `git commit`)
4. ✅ Änderungen pushen (verwende `run_terminal_cmd` mit `git push origin {branch_name}`)
5. ✅ PR erstellen (verwende `run_terminal_cmd` mit `gh pr create` - inkl. Labels und Base-Branch: {base_branch})
6. ✅ Issue kommentieren (verwende `run_terminal_cmd` mit `gh issue comment`)

**WICHTIG:**
- Für ALLE Terminal-Befehle (git, gh) musst du das `run_terminal_cmd` Tool verwenden!
- **SCHRITT 2 IST OBLIGATORISCH** - ohne `/tmp/agent-summary.md` wird der PR mit generischem Text erstellt!

**Beginne jetzt mit der Analyse und Implementierung!**
"""

    output_file = os.environ.get('OUTPUT_FILE', '/tmp/fix-prompt.md')

    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(prompt)
        print(f"✅ Prompt created for issue #{issue_num} -> {output_file}", file=sys.stderr)
        sys.exit(0)
    except Exception as e:
        print(f"❌ Error writing prompt file: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    create_fix_prompt()

