#!/usr/bin/env python3
"""
Erstellt eine PR-Body für den AI Issue Fix Workflow.
Behandelt sicher alle Sonderzeichen.
"""
import os
import sys

def create_pr_body():
    """Erstellt die PR-Body aus Environment-Variablen."""
    issue_num = os.environ.get('ISSUE_NUM', '')
    issue_title = os.environ.get('ISSUE_TITLE', '')
    issue_url = os.environ.get('ISSUE_URL', '')

    if not issue_num:
        print("❌ Error: ISSUE_NUM environment variable not set", file=sys.stderr)
        sys.exit(1)

    pr_body = f"""## 🤖 AI-Generated Fix for Issue #{issue_num}

This PR was automatically generated by the AI Issue Fix workflow to resolve issue #{issue_num}.

**Issue:** {issue_title}
**Issue URL:** {issue_url}

### Changes
This PR contains the AI-generated fix for the issue. Please review carefully before merging.

### Review Checklist
- [ ] Code changes are correct
- [ ] Tests pass (if applicable)
- [ ] No breaking changes introduced
- [ ] Follows project architecture patterns

---
*This PR was created automatically. Please review and test before merging.*"""

    output_file = os.environ.get('OUTPUT_FILE', '/tmp/pr-body.txt')

    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(pr_body)
        print(f"✅ PR body created for issue #{issue_num} -> {output_file}", file=sys.stderr)
        # Ausgabe für Verwendung in Shell
        print(pr_body)
        sys.exit(0)
    except Exception as e:
        print(f"❌ Error writing PR body file: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    create_pr_body()

