#!/usr/bin/env python3
"""
Erstellt einen Fix-Prompt für den AI Issue Fix Workflow.
Behandelt sicher alle Sonderzeichen in Issue-Beschreibungen.
"""
import os
import sys

def create_fix_prompt():
    """Erstellt den Fix-Prompt aus Environment-Variablen."""
    issue_num = os.environ.get('ISSUE_NUM', '')
    issue_title = os.environ.get('ISSUE_TITLE', '')
    issue_url = os.environ.get('ISSUE_URL', '')
    issue_body = os.environ.get('ISSUE_BODY', '')
    branch_name = os.environ.get('BRANCH_NAME', '')
    base_branch = os.environ.get('BASE_BRANCH', 'main')

    if not issue_num:
        print("❌ Error: ISSUE_NUM environment variable not set", file=sys.stderr)
        sys.exit(1)

    prompt = f"""Du arbeitest in einem GitHub Actions Runner mit vollständigem Zugriff auf Git und GitHub CLI.

**WICHTIG - Terminal-Befehle:**
Du MUSST Terminal-Befehle direkt ausführen können. Verwende das `run_terminal_cmd` Tool für alle Git- und GitHub CLI-Befehle.
Die Terminal-Umgebung ist vollständig konfiguriert und bereit für deine Befehle.

# Aufgabe: Issue #{issue_num} beheben

**Issue-Titel:** {issue_title}
**Issue-URL:** {issue_url}

**Issue-Beschreibung:**
{issue_body}

## Deine Aufgabe:

1. **Analysiere das Problem** im Issue
2. **Finde die betroffenen Dateien** (nutze `git`, `gh`, oder lese Dateien direkt)
3. **Implementiere die Lösung** direkt im Code
4. **Erstelle Commits** mit `git add` und `git commit`
5. **Pushe die Änderungen** mit `git push` (Branch: {branch_name})
6. **Erstelle einen Pull Request** mit `gh pr create` und verlinke ihn mit dem Issue
7. **Teste deine Lösung** (falls Tests vorhanden sind)

## WICHTIG - Du MUSST folgendes tun:

### Git-Operationen:
- **WICHTIG:** Verwende das `run_terminal_cmd` Tool für ALLE Git-Befehle!
- **Git-Befehle ausführen:** Nutze `run_terminal_cmd` mit Befehlen wie `git add`, `git commit`, `git push`
- **Erstelle sinnvolle Commits:** Jeder Commit sollte eine logische Änderungseinheit sein
- **Commit-Messages:** Verwende klare, beschreibende Messages (z.B. "fix: resolve issue #{issue_num}")
- **Keine leeren Commits:** Nur committen wenn tatsächlich Änderungen gemacht wurden
- **Keine Force-Push:** Nutze normale `git push origin {branch_name}`
- **Git ist bereits konfiguriert:** User und Email sind gesetzt, du musst sie nicht nochmal setzen

### Pull Request erstellen:
**NACH dem Push der Änderungen MUSST du einen Pull Request erstellen:**

1. **PR-Titel:** `fix: Resolve issue #{issue_num} - {issue_title}`

2. **PR-Body:** Erstelle eine aussagekräftige Beschreibung:
   ```markdown
   ## 🤖 AI-Generated Fix for Issue #{issue_num}

   This PR was automatically generated by the AI Issue Fix workflow to resolve issue #{issue_num}.

   **Issue:** {issue_title}
   **Issue URL:** {issue_url}

   ### Changes
   This PR contains the AI-generated fix for the issue. Please review carefully before merging.

   ### Review Checklist
   - [ ] Code changes are correct
   - [ ] Tests pass (if applicable)
   - [ ] No breaking changes introduced
   - [ ] Follows project architecture patterns

   ---
   *This PR was created automatically. Please review and test before merging.*
   ```

3. **PR erstellen mit GitHub CLI:**
   **WICHTIG:** Verwende `run_terminal_cmd` für alle `gh`-Befehle!

   Zuerst PR-Body in Datei schreiben (verwende `write` Tool):
   - Erstelle `/tmp/pr-body.txt` mit dem PR-Body-Inhalt

   Dann PR erstellen (verwende `run_terminal_cmd`):
   ```
   gh pr create --title "fix: Resolve issue #{issue_num} - {issue_title}" --body-file /tmp/pr-body.txt --base {base_branch} --head {branch_name} --label "ai-generated" --label "automated"
   ```

   **WICHTIG:** Schreibe den PR-Body zuerst in eine Datei (`/tmp/pr-body.txt`), um Sonderzeichen-Probleme zu vermeiden!

4. **Issue verlinken:**
   Nach erfolgreicher PR-Erstellung füge einen Kommentar zum Issue hinzu (verwende `run_terminal_cmd`):
   ```
   gh issue comment {issue_num} --body "🤖 AI has created a fix for this issue: PR #<PR_NUMBER>"
   ```

   Ersetze `<PR_NUMBER>` mit der tatsächlichen PR-Nummer aus dem `gh pr create` Output.

5. **Labels prüfen:**
   Falls die Labels "ai-generated" oder "automated" nicht existieren, erstelle sie nicht - der Workflow kümmert sich darum.

## Git-Konfiguration:

Git ist bereits konfiguriert:
- User: github-actions[bot]
- Email: github-actions[bot]@users.noreply.github.com
- Branch: {branch_name}
- Remote: origin (bereits konfiguriert)

## Projektkontext:

Das Projekt verwendet:
- **Clean Architecture** mit 4 Schichten: Domain → Application → Infrastructure → Framework
- **Result-Pattern** statt Exceptions (siehe ADR-0001)
- **SOLID-Prinzipien** durchgängig
- **Port-Adapter-Pattern** für Foundry VTT Version-Kompatibilität
- **Dependency Inversion Principle (DIP)**: Abhängigkeiten nur zu Interfaces

## Code-Qualität:

- Halte dich an die bestehenden Architektur-Patterns
- Verwende das Result-Pattern für Fehlerbehandlung
- Respektiere die Schichttrennung (Clean Architecture)
- Füge Tests hinzu, wenn möglich

## Output:

Nachdem du die Änderungen gemacht, committed, gepusht und die PR erstellt hast, gib eine kurze Zusammenfassung aus:
- Welche Dateien wurden geändert?
- Was wurde behoben?
- PR-Nummer und Link (falls erfolgreich erstellt)
- Gibt es besondere Überlegungen für den Reviewer?

## Zusammenfassung der Schritte:

1. ✅ Code-Änderungen implementieren (verwende `search_replace` oder `write` Tool)
2. ✅ Commits erstellen (verwende `run_terminal_cmd` mit `git add` und `git commit`)
3. ✅ Änderungen pushen (verwende `run_terminal_cmd` mit `git push origin {branch_name}`)
4. ✅ PR-Body in `/tmp/pr-body.txt` schreiben (verwende `write` Tool)
5. ✅ PR erstellen (verwende `run_terminal_cmd` mit `gh pr create` - inkl. Labels und Base-Branch: {base_branch})
6. ✅ Issue kommentieren (verwende `run_terminal_cmd` mit `gh issue comment`)

**WICHTIG:** Für ALLE Terminal-Befehle (git, gh) musst du das `run_terminal_cmd` Tool verwenden!

**Beginne jetzt mit der Analyse und Implementierung!**
"""

    output_file = os.environ.get('OUTPUT_FILE', '/tmp/fix-prompt.md')

    try:
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(prompt)
        print(f"✅ Prompt created for issue #{issue_num} -> {output_file}", file=sys.stderr)
        sys.exit(0)
    except Exception as e:
        print(f"❌ Error writing prompt file: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    create_fix_prompt()

